apps/movies/urls.py
from django.conf.urls import url, include
from apps.movies import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'movies'

movies_patterns = [
    url(r'^inicio/$', views.movie_list, name='home'),
    url(r'^(?P<pk>[0-9]+)/$', views.movie_detail, name='movies-detail'),
    url(r'^crear/$', views.movie_create, name='movies-create'),
    url(r'^(?P<pk>[0-9]+)/editar/$', views.movie_update, name='movies-edit'),
    url(r'^(?P<pk>[0-9]+)/eliminar/$', views.movie_delete, name='movies-delete')
]

urlpatterns = [
    url(r'^$', views.log_in, name='log-in'),
    url(r'^log-out/$', views.log_out, name='log-out'),
    url(r'^Especialidad/$', views.category_list, name='category-list'),
    url(r'^Reservas/', include(movies_patterns))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

crud/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # registrar urls de nuestra aplicacion movies
    url(r'^', include('apps.movies.urls'))
]

# Esto no es adecuado para produccion !! 
# Para mas informacion de como servir estos archivos en: 
# https://docs.djangoproject.com/en/1.11/howto/static-files/deployment/
urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

apps/movies/models.py
from django.db import models
from django.urls import reverse_lazy


# Create your models here.

class BaseName(models.Model):
    name = models.CharField(max_length=150, verbose_name='Nombre')
    created = models.DateTimeField(auto_now=False, auto_now_add=True)
    updated = models.DateTimeField(auto_now=True, auto_now_add=False)

    class Meta:
        abstract = True

    def __str__(self):
        return self.name


class Categories(BaseName):
    minimum_age = models.IntegerField(verbose_name='Edad Minima')

    class Meta:
        verbose_name = 'Reserva'
        verbose_name_plural = 'Especialidades'


class Movies(BaseName):
    description = models.CharField(max_length=256, verbose_name='Teléfono')
    image = models.ImageField(upload_to='movies', verbose_name='Imagen Carnet')
    release_date = models.DateField(verbose_name='Fecha de atención')
    category = models.ForeignKey(Categories, on_delete=models.CASCADE, verbose_name='Especialidad')

    class Meta:
        verbose_name = 'Reserva'
        verbose_name_plural = 'Reservas'

    def get_edit_url(self):
        return reverse_lazy('movies:movies-edit', kwargs={'pk': self.pk})

    def get_delete_url(self):
        return reverse_lazy('movies:movies-delete', kwargs={'pk': self.pk})

    def get_detail_url(self):
        return reverse_lazy('movies:movies-detail', kwargs={'pk': self.pk})

apps/movies/forms.py
from django import forms
from .models import Movies


class MoviesForm(forms.ModelForm):
    class Meta:
        model = Movies
        fields = '__all__'


class LoginForm(forms.Form):
    username = forms.CharField(label='Usuario')
    password = forms.CharField(widget=forms.PasswordInput, label="Contraseña")

apps/movies/views.py
from django.contrib.auth.decorators import login_required
from django.http import Http404
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import authenticate, login, logout
from .models import Movies, Categories
from .forms import MoviesForm, LoginForm


# Create your views here.


def log_in(request):
    # Diccionario que almacena los datos que enviamos a la vista
    form = LoginForm(
        request.POST or None
    )
    context = {'message': None, 'form': form}
    if request.POST and form.is_valid():
        # Verificar credenciales
        # Devuelve un objeto User si las credenciales son válidas.
        # Si las credenciales no son válidas, devuelve None
        user = authenticate(**form.cleaned_data)
        if user is not None:
            # Verificar si el usuario esta activo
            if user.is_active:
                # Adjuntar usuario autenticado a la sesión actual
                login(request, user)
                # Redireccionar a una vista utilizando el nombre de la url
                return redirect('movies:home')
            else:
                context['message'] = 'El usuario ha sido desactivado'
        else:
            context['message'] = 'Usuario o contraseña incorrecta'
    return render(request, 'movies/login.html', context)


# decorador para restringir el acceso a solo usuarios autenticados
@login_required
def log_out(request):
    logout(request)
    return redirect('movies:log-in')


@login_required
def movie_list(request):
    movies = Movies.objects.all()
    return render(request, 'movies/index.html', {'movies': movies})


@login_required
def movie_detail(request, pk):
    try:
        # recuperamos el objeto mediante la
        # API de abstracción de base de datos
        # que ofrece Django
        m = Movies.objects.get(pk=pk)
    except Movies.DoesNotExist:
        raise Http404("Esta pelicuala no existe")

    # version con shortcuts de django, equivalente al codigo anterior
    # m = get_object_or_404(Movies, pk=pk)
    return render(request, 'movies/detail.html', {'movie': m})


@login_required
def movie_create(request, **kwargs):
    # Intanciamos la clase form
    # si el diccionario request.POST no esta vacio
    # la instancia se creara con dichos datos, sino estara vacia
    form = MoviesForm(
        request.POST or None,
        request.FILES or None
    )
    # Comprobamos que la peticion es del motodo POST
    # y que el formulario es valido
    if request.POST and form.is_valid():
        # Guardamos el objeto
        form.save()
        # redirigir a una nueva URL
        return redirect('movies:home')
    return render(request, 'movies/form.html', {'form': form})


@login_required
def movie_update(request, **kwargs):
    # recuperamos el objeto a actualizar
    movie = Movies.objects.get(pk=kwargs.get('pk'))
    # inicializamos el formulario con el objeto recuperado
    form = MoviesForm(
        request.POST or None,
        instance=movie
    )
    if request.POST and form.is_valid():
        form.save()
        return redirect('movies:home')
    return render(request, 'movies/form.html', {'form': form})


@login_required
def movie_delete(request, **kwargs):
    movie = Movies.objects.get(pk=kwargs.get('pk'))
    movie.delete()
    return redirect('movies:home')


@login_required
def category_list(request):
    categories = Categories.objects.all()
    return render(request, 'movies/category/category_list.html', {'categories': categories})

apps/movies/templates/movies/category/category_list.html
{% extends 'movies/fragments/base.html' %}
{% block main-content %}
    <div class="row">
        <div class="col s12">
            {% if not categories %}
                <div class="card-panel red">
                    <span class="white-text">No hay registros actualmente</span>
                </div>
            {% else %}
                <table class="striped centered">
                    <thead>
                    <tr>
                        <th width="20%">Nombre</th>
                        <th>Edad minima</th>
                        <th>Creacion</th>
                        <th>Ultima actualizacion</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for category_item in categories %}
                        <tr>
                            <td width="20%">{{ category_item.name }}</td>
                            <td>{{ category_item.minimum_age }}</td>
                            <td>{{ category_item.created | timesince }}</td>
                            <td>{{ category_item.updated | timesince }}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            {% endif %}
        </div>
    </div>
{% endblock %}

apps/movies/templates/movies/detail.html
{% extends 'movies/fragments/base.html' %}
{% block main-content %}
<div class="row">
    <div class="col s8 offset-s2">
        <div class="card">
            <div class="card-image">
                <img src=https://novedadescentromed.cl/imagenes/banner_003.jpg height="250px" width="400px"
                    style="object-fit: cover;">
            </div>
            <div class="card-content">
                <span class="card-title">Atención CESFAM</span>
                <p><b>Fecha de Atención:</b> {{ movie.release_date }}</p>
                <p><b>Especialidad: </b> {{ movie.category }}</p>
                <p><b>Teléfono: </b>{{ movie.description }}</p>
                <p><b>Creada: </b>{{ movie.created }}</p>
                <p><b>Ultima actualización: </b>{{ movie.updated }}</p>
            </div>
            <div class="card-action">
                <a href="{{ movie.get_edit_url }}">Editar</a>
                <a href="{{ movie.get_delete_url }}">Eliminar</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

apps/movies/templates/movies/form.html
{% extends 'movies/fragments/base.html' %}
{% block main-content %}
    <div class="row">
        <div class="col s8 offset-s2">
            {% include 'movies/fragments/forms.html' %}
        </div>
    </div>
{% endblock %}

apps/movies/templates/movies/fragments/base.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>Document</title>
    <!--Import Google Icon Font-->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">

    <style>
        .errorlist {
            color: #F44336 !important;
        }
    </style>
</head>
<body>
<nav class="light-blue lighten-1" role="navigation">
    <div class="nav-wrapper container">
        <a id="logo-container" href="{% url 'movies:home' %}" class="brand-logo">Solicitud horas CESFAM.</a>
        {% if request.user.is_authenticated %}
            <ul class="right hide-on-med-and-down">
                <li><a href="{% url 'movies:home' %}">Reservas</a></li>
                <li><a href="{% url 'movies:category-list' %}">Especialidades</a></li>
                <li><a href="{% url 'movies:log-out' %}">Salir </a></li>
            </ul>
            <ul id="nav-mobile" class="side-nav">
                <li><a href="{% url 'movies:home' %}">Reservas</a></li>
                <li><a href="{% url 'movies:category-list' %}">Especialidades</a></li>
                <li><a href="{% url 'movies:log-out' %}">Salir </a></li>
            </ul>
            <a href="#" data-activates="nav-mobile" class="button-collapse"><i class="material-icons">menu</i></a>
        {% endif %}
    </div>
</nav>
<div class="container">
    <div class="section">
        {% block main-content %}{% endblock %}
    </div>
    <br><br>
</div>

<script type="text/javascript" src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
<!-- Compiled and minified JavaScript -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js"></script>

<script>
    $(document).ready(function () {
        $('select').material_select();

         $('.datepicker').pickadate({
            selectMonths: true, // Creates a dropdown to control month
            selectYears: 15, // Creates a dropdown of 15 years to control year,
            today: 'Today',
            clear: 'Clear',
            close: 'Ok',
            closeOnSelect: false // Close upon selecting a date,
          });
    });
</script>

</body>
</html>

apps/movies/templates/movies/fragments/forms.html
{% load widget_tweaks %}
<form enctype="multipart/form-data" method="post" >
    {% csrf_token %}
    {% for field in form %}
        <div class="row" >
            {% if field.errors %}
               {{ field.errors }}
            {% endif %}
            <div class="{% if field|widget_type == 'clearablefileinput' %}  browser-default{% endif %} input-field col s12">
                {% comment %}
                     De esta manera podemos hacer formularios reutilizables con widget_tweaks,
                     tambien podemos añadir librerias a nuestro gusto
                {% endcomment %}
                {% if field|widget_type == 'clearablefileinput' %}
                    <p class="grey-text"> {{ field.label }} </p>
                    {% render_field field class+="validate" %}
                {% else %}
                    {% render_field field class+="validate" %}
                    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                {% endif %}
            </div>
        </div>
    {% endfor %}

    <div class="row">
        <button class="btn waves-effect waves-light right red darken-1" type="submit" name="action">Entrar
            <i class="material-icons right">send</i>
        </button>
    </div>
</form>

apps/movies/templates/movies/index.html
{% extends 'movies/fragments/base.html' %}
{% block main-content %}
<div class="row">
    <div class="col s12">
        <a class="waves-effect waves-light btn right red darken-1" href="{% url 'movies:movies-create' %}"><i
                class="material-icons left">add</i>Agregar nuevo</a>
    </div>
</div>
<div class="row">
    <div class="col s12">
        {% if not movies %}
        <div class="card-panel red">
            <span class="white-text">No hay registros actualmente</span>
        </div>
        {% else %}
        <table class="striped centered">
            <thead>
                <tr>
                    <th width="20%">Nombre</th>
                    <th>Teléfono</th>
                    <th>Fecha de Atención</th>
                    <th>Especialidad</th>
                    <th width="20%">Opciones</th>
                </tr>
            </thead>
            <tbody>
                {% for movie in movies %}
                <tr>
                    <td width="20%">{{ movie.name }}</td>
                    <td>{{ movie.description | truncatechars:120 }}</td>
                    <td>{{ movie.release_date }}</td>
                    <td>{{ movie.category }}</td>
                    <td width="20%">
                        <a class="btn-floating btn-small waves-effect waves-light red"
                            href="{{ movie.get_edit_url }}"><i class="material-icons">edit</i></a>
                        <a class="btn-floating btn-small waves-effect waves-light blue"
                            href="{{ movie.get_delete_url }}"><i class="material-icons">delete</i></a>
                        <a class="btn-floating btn-small waves-effect waves-light green"
                            href="{{ movie.get_detail_url }}"><i class="material-icons">visibility</i></a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        {% endif %}
    </div>
</div>
{% endblock %}

apps/movies/templates/movies/login.html
{% extends 'movies/fragments/base.html' %}
{% block main-content %}

    <div class="center-align">
        <img src="https://i.ibb.co/SxwjQ9Q/cesfam-logo.png" alt="movie icon"
             height="200px" width="200px">
    </div>

    <div class="row">
        <div class="col s8 offset-s2">

            {% if message %}
                <div class="card-panel red darken-1">
                  <span class="white-text">
                      {{ message }}
                  </span>
                </div>
            {% endif %}

            {% include 'movies/fragments/forms.html' %}

        </div>
    </div>
{% endblock %}